# Generated by Django 4.2.6 on 2023-11-21 08:59

from django.db import migrations, models
import django.db.models.deletion
import vacancies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('about_company', models.TextField()),
                ('position_overview', models.TextField()),
                ('responsibilities', models.TextField()),
                ('qualifications', models.TextField()),
                ('salary', models.IntegerField()),
                ('industry', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Freelance', 'Freelance'), ('Internship', 'Internship')], max_length=100)),
                ('work_mode', models.CharField(choices=[('On-Site', 'On-Site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('Flexible', 'Flexible')], max_length=100)),
                ('posting_date', models.DateField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_recruiter', to='companies.recruiter')),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to=vacancies.models.get_upload_path)),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to=vacancies.models.get_upload_path)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_applications', to='candidates.candidate')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_applications', to='companies.recruiter')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_applications', to='vacancies.vacancy')),
            ],
        ),
    ]
