# Generated by Django 4.2.6 on 2023-10-14 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='location_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='location_country',
            new_name='country',
        ),
    ]
