# Generated by Django 4.2.6 on 2023-10-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_rename_location_city_vacancy_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='slug',
        ),
    ]
