# Generated by Django 4.2.6 on 2023-10-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_remove_vacancy_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='description',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='about_company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='key_responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='position_overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
