# Generated by Django 4.2.6 on 2023-10-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('vacancies', '0004_remove_vacancy_description_vacancy_about_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacancy_recruiter', to='companies.recruiter'),
        ),
    ]
