# Generated by Django 4.2.6 on 2023-11-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_rename_submission_date_application_submissiondate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applicantEmail',
            new_name='applicant_email',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='applicantName',
            new_name='applicant_name',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='applicantPhone',
            new_name='applicant_phone',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='motivationLetter',
            new_name='motivation_letter',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='submissionDate',
            new_name='submission_date',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='aboutCompany',
            new_name='about_company',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='employmentType',
            new_name='employment_type',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='keyResponsibilities',
            new_name='key_responsibilities',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='positionOverview',
            new_name='position_overview',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='postingDate',
            new_name='posting_date',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='workMode',
            new_name='work_mode',
        ),
    ]
