# Generated by Django 4.2.6 on 2023-11-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_rename_applicantemail_application_applicant_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
