# Generated by Django 4.2.6 on 2023-11-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_remove_application_applicant_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='motivation_letter',
            new_name='cover_letter',
        ),
    ]
