# Generated by Django 4.2.6 on 2023-11-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_rename_motivation_letter_application_cover_letter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applicant',
            new_name='candidate',
        ),
    ]
