# Generated by Django 4.2.6 on 2023-11-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_rename_applicant_application_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='company',
        ),
    ]
