# Generated by Django 4.2.6 on 2023-11-11 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_recruiter_company'),
        ('candidates', '0008_remove_candidate_birth_date'),
        ('vacancies', '0012_remove_vacancy_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='recruiter',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_applications', to='companies.recruiter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_applications', to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_applications', to='vacancies.vacancy'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='recruiter',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_recruiter', to='companies.recruiter'),
            preserve_default=False,
        ),
    ]
