databases:
  - name: backend_job_board
    databaseName: backend_job_board
    user: admin

services:
  - type: web
    name: backend_job_board
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend_job_board.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: backend_job_board
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.5