# Generated by Django 4.2.6 on 2023-11-07 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='name',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
