# Generated by Django 4.2.6 on 2023-11-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_recruiter_email_remove_recruiter_linkedin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.RemoveField(
            model_name='company',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
    ]
