# Generated by Django 4.2.6 on 2023-11-07 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_company_country_remove_company_linkedin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='recruiter',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_recruiter', to='companies.recruiter'),
            preserve_default=False,
        ),
    ]
