# Generated by Django 4.2.6 on 2023-11-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_recruiter_company_company_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
