# Generated by Django 4.2.6 on 2023-11-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_recruiter_birth_date_recruiter_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='birth_date',
        ),
    ]
