# Generated by Django 4.2.6 on 2023-11-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_recruiter_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
