# Generated by Django 4.2.6 on 2023-11-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='linkedIn',
        ),
        migrations.AddField(
            model_name='candidate',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
