# Generated by Django 4.2.6 on 2023-11-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_remove_candidate_email_remove_candidate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
