# Generated by Django 4.2.6 on 2023-11-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_alter_candidate_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='birth_date',
        ),
    ]
