# Generated by Django 4.2.6 on 2023-11-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_group',
            field=models.CharField(default='candidates', max_length=50),
            preserve_default=False,
        ),
    ]
